name: Deployment-Pipeline

on:
  push:
  pull_request:
    branches:
    - main
    - branch_01

jobs:
  build_image:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: docker login
          run: |
            docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
        - name: Build the Docker image
          run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_USER}}/${{secrets.DOCKER_IMAGE_NAME}}

        - name: Docker Push
          run: docker push ${{secrets.DOCKER_USER}}/${{secrets.DOCKER_IMAGE_NAME}}

  deploy_aci:
    runs-on: ubuntu-latest
    needs: [build_image]
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}

      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az account show
            az container create --resource-group ${{vars.AZURE_RESOURCE_GROUP}} --name ${{vars.AZURE_CONTAINER_NAME}} \
            --image ${{secrets.DOCKER_USER}}/${{secrets.DOCKER_IMAGE_NAME}} \
            --dns-name-label ${{vars.DNS}} --ports ${{vars.PORT}}